@contentType = application/json 

POST   https://glc-server-production.up.railway.app/acc' HTTP/1.1
Content-Type: {{contentType}}

{
    
    "fullName": "Samson",
    "phoneNumber":"0940317011",
    "city":"String",
    "subCity": "String",
    "educationLevel": "String",
    "schoolName": "String",
    "fieldofStudy": "String",
    "whatWork": "String",
    "placeWork": "String",
    "whereWork": "String"





}
###


POST   https://glc-server-production.up.railway.app/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "gloriouslifechurch@gmail.com",
  "password": "@gloriouslife"
}

###

POST   https://glc-server-production.up.railway.app/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "gloriouslifechurch@gmail.com",
  "password": "@gloriouslife"
}

